dbdata:
    image: postgres
    command: true

db:
    extends: 
        file: common.yml
        service: db_base
    volumes_from:
        - dbdata    
djangoprod:
    extends: 
        file: common.yml
        service: django_base
    entrypoint: []
    command: gunicorn -c /etc/gunicorn/gunicorn.conf.py wsgi:application
    volumes:
        - "backend:/src"
        - "frontend/dist:/static"
        - "conf/gunicorn.conf.py:/etc/gunicorn/gunicorn.conf.py:ro"
        - "logs/gunicorn:/tmp/logs/gunicorn"
        - "logs/app:/tmp/logs/app"
    links:
        - db
    environment:
        DJANGO_SETTINGS_MODULE: conf.settings_prod
        NUM_WORKERS: 4
nginxprod:
    image: nginx
    links:
        - djangoprod
    volumes: 
        - "frontend/dist:/static:ro"
        - "conf/ssl:/etc/nginx/ssl:ro"
        - "logs/nginx:/tmp/logs"
        - "media:/media"
# COMMENT LINE BELOW IF CONFIGURING SSL ON INCLUDED NGINX
        - "conf/nginx.conf:/etc/nginx/nginx.conf:ro"
# UNCOMMENT LINE BELOW IF CONFIGURING SSL ON INCLUDED NGINX
#       - "conf/nginx_ssl.conf:/etc/nginx/nginx.conf:ro"

    ports:
        - "80:80"
# UNCOMMENT BELOW IF USING SSL
#        - "443:443"

